"""
Priority-4 workflow for macro 500um fatigue simulation quality:
1) scale-consistency report
2) 500um mesh-convergence runs
3) displacement-BC + dual-backstress calibration sweep (0.2/0.4/0.6/0.8%)
4) unified validation pack with one comparison standard table

This script is intentionally orchestration-focused and reuses:
- sim/tests/run_coupled_validation_bundle.py
- sim/tests/run_multi_amplitude_validation_pack.py
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import subprocess
import sys
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any

import numpy as np
import yaml  # type: ignore


ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from sim.energy import FractureParameters
from sim.tests.run_virtual_cycle_config import _normalize_config, _resolve_payload


def _now_tag() -> str:
    return datetime.now().strftime("%Y%m%d_%H%M%S")


def _load_vc(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(raw, dict):
        raise ValueError(f"Config root must be mapping: {path}")
    vc_raw, _ = _resolve_payload(raw)
    return _normalize_config(vc_raw)


def _dump_yaml(path: Path, vc: dict[str, Any]) -> None:
    payload = {"description": f"auto-generated by run_priority4_pipeline: {path.stem}", "virtual_cycle": vc}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(yaml.safe_dump(payload, sort_keys=False, allow_unicode=True), encoding="utf-8")


def _unit_scale_and_name(length_m: float) -> tuple[float, str]:
    if length_m >= 1.0e-3:
        return 1.0e3, "mm"
    if length_m >= 1.0e-6:
        return 1.0e6, "um"
    return 1.0, "m"


def _direction_modulus_gpa(c11: float, c12: float, c44: float, direction: tuple[float, float, float]) -> float:
    c11 = float(c11)
    c12 = float(c12)
    c44 = float(c44)
    a = c11 - c12
    b = c11 + 2.0 * c12
    if abs(a) < 1e-14 or abs(b) < 1e-14 or abs(c44) < 1e-14:
        return float("nan")
    s11 = (c11 + c12) / (a * b)
    s12 = -c12 / (a * b)
    s44 = 1.0 / c44
    l = np.asarray(direction, dtype=float)
    n = float(np.linalg.norm(l))
    if n <= 1e-14:
        l = np.array([1.0, 1.0, 1.0], dtype=float)
        n = float(np.linalg.norm(l))
    l = l / n
    q = float(l[0] * l[0] * l[1] * l[1] + l[1] * l[1] * l[2] * l[2] + l[2] * l[2] * l[0] * l[0])
    inv_e = s11 - 2.0 * (s11 - s12 - 0.5 * s44) * q
    if abs(inv_e) < 1e-14:
        return float("nan")
    return 1.0 / inv_e


def _arc_notch_effective_width(vc: dict[str, Any], dx: float) -> tuple[float | None, float | None, float | None]:
    arc = vc.get("arc_notch")
    if not isinstance(arc, dict):
        return None, None, None
    xr = arc.get("x_range")
    if not (isinstance(xr, (list, tuple)) and len(xr) == 2):
        return None, None, None
    x0 = float(min(xr[0], xr[1]))
    x1 = float(max(xr[0], xr[1]))
    raw_w = max(0.0, x1 - x0)
    min_cells = int(arc.get("min_cells_x", vc.get("arc_notch_min_cells_x", 2)))
    min_cells = max(1, min_cells)
    min_w = float(min_cells) * float(dx)
    eff_w = max(raw_w, min_w)
    return raw_w, eff_w, float(min_cells)


def _write_json(path: Path, obj: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in fieldnames})


def _poly_area_abs(x: np.ndarray, y: np.ndarray) -> float:
    if len(x) < 3:
        return 0.0
    xc = np.concatenate([x, x[:1]])
    yc = np.concatenate([y, y[:1]])
    return float(abs(0.5 * np.sum(xc[:-1] * yc[1:] - xc[1:] * yc[:-1])))


def _load_stress_strain(csv_path: Path, stress_ref_gpa: float) -> tuple[np.ndarray, np.ndarray]:
    with csv_path.open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    eps = np.array([float(r.get("macro_strain", 0.0)) for r in rows], dtype=float)
    if rows and ("sig_xx_nd" in rows[0]):
        sig = np.array([float(r.get("sig_xx_nd", 0.0)) for r in rows], dtype=float) * stress_ref_gpa * 1000.0
    else:
        sig = np.array([float(r.get("sig_xx_GPa", 0.0)) for r in rows], dtype=float) * 1000.0
    return eps, sig


def _loop_closure_ratio(stress_strain_csv: Path, cycle_points: int, stress_ref_gpa: float) -> float:
    if not stress_strain_csv.exists():
        return float("nan")
    eps, sig = _load_stress_strain(stress_strain_csv, stress_ref_gpa=stress_ref_gpa)
    if eps.size < cycle_points or cycle_points <= 2:
        return float("nan")
    x = eps[-cycle_points:]
    y = sig[-cycle_points:]
    area = _poly_area_abs(x, y)
    denom = (float(np.max(x) - np.min(x)) * float(np.max(y) - np.min(y))) + 1e-16
    return area / denom


def _hardening_ratio(curve_csv: Path) -> float:
    if not curve_csv.exists():
        return float("nan")
    with curve_csv.open("r", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    if len(rows) < 3:
        return float("nan")
    eps = np.array([float(r.get("eps_p_cum", 0.0)) for r in rows], dtype=float)
    sig = np.array([float(r.get("sigma_a_MPa", 0.0)) for r in rows], dtype=float)
    de0 = eps[1] - eps[0]
    de1 = eps[-1] - eps[-2]
    if abs(de0) < 1e-20 or abs(de1) < 1e-20:
        return float("nan")
    s0 = (sig[1] - sig[0]) / de0
    s1 = (sig[-1] - sig[-2]) / de1
    return abs(float(s0)) / (abs(float(s1)) + 1e-12)


def _run_validation_case(
    vc_base: dict[str, Any],
    amp_pct: float,
    cfg_dir: Path,
    out_dir: Path,
    run_dir: Path,
    python_bin: str,
    cycles: int,
    cycle_points: int,
    case_tag: str,
) -> dict[str, Any]:
    vc = json.loads(json.dumps(vc_base))
    vc["max_strain"] = float(amp_pct / 100.0)
    vc["task"] = f"{vc.get('task', 'priority4')}_{case_tag}"
    cfg_path = cfg_dir / f"{case_tag}.yaml"
    _dump_yaml(cfg_path, vc)

    cmd = [
        python_bin,
        "sim/tests/run_coupled_validation_bundle.py",
        "--config",
        str(cfg_path),
        "--out-dir",
        str(out_dir),
        "--run-dir",
        str(run_dir),
        "--cycles",
        str(int(cycles)),
        "--cycle-points",
        str(int(cycle_points)),
        "--keep-old-images",
    ]
    proc = _run_subprocess(cmd, ROOT, check=False)
    summary_path = out_dir / "validation_bundle_summary.json"
    ok = summary_path.exists() and proc.returncode == 0
    return {
        "ok": bool(ok),
        "returncode": int(proc.returncode),
        "error_tail": (proc.stderr or proc.stdout or "").strip()[-1500:],
        "summary_path": str(summary_path),
        "config_path": str(cfg_path),
        "out_dir": str(out_dir),
        "run_dir": str(run_dir),
    }


def _scale_consistency_step(vc: dict[str, Any], out_dir: Path) -> dict[str, Any]:
    shape = tuple(int(v) for v in vc.get("grid_shape", (24, 12, 4)))
    spacing = tuple(float(v) for v in vc.get("grid_spacing", (1.0, 1.0, 1.0)))
    dx, dy, dz = spacing
    nx, ny, nz = shape

    lx = (nx - 1) * dx
    ly = (ny - 1) * dy
    lz = (nz - 1) * dz
    _, u_name = _unit_scale_and_name(max(lx, ly, lz))
    sc = 1.0e6 if u_name == "um" else (1.0e3 if u_name == "mm" else 1.0)

    frac = FractureParameters()
    l0 = float(vc.get("l0", frac.l0))
    gc = float(vc.get("gc", frac.gc))
    toughness_scale = float(vc.get("toughness_scale", 1.0))
    gc_eff = gc * toughness_scale

    stress_ref_gpa = float(vc.get("stress_ref_gpa", 168.4))
    c11_phys = float(vc.get("c11", 1.0)) * stress_ref_gpa
    c12_phys = float(vc.get("c12", 0.7209)) * stress_ref_gpa
    c44_phys = float(vc.get("c44", 0.4477)) * stress_ref_gpa
    e111 = _direction_modulus_gpa(c11_phys, c12_phys, c44_phys, (1.0, 1.0, 1.0))

    lref = min(v for v in spacing if v > 0.0)
    l0_phys_est = l0 * lref

    raw_w, eff_w, min_cells = _arc_notch_effective_width(vc, dx)
    max_strain = float(vc.get("max_strain", 0.0))
    u_peak = max_strain * lx

    report = {
        "grid_shape": [nx, ny, nz],
        "grid_spacing_m": [dx, dy, dz],
        "domain_size_m": [lx, ly, lz],
        f"domain_size_{u_name}": [lx * sc, ly * sc, lz * sc],
        "nondim_reference": {
            "stress_ref_gpa": stress_ref_gpa,
            "c11_phys_gpa": c11_phys,
            "c12_phys_gpa": c12_phys,
            "c44_phys_gpa": c44_phys,
            "E111_phys_gpa_est": e111,
        },
        "fracture_scaling": {
            "l0_nd": l0,
            "gc_nd": gc,
            "toughness_scale": toughness_scale,
            "gc_effective_nd": gc_eff,
            "l0_phys_est_m": l0_phys_est,
            "l0_over_dx": l0_phys_est / max(dx, 1e-20),
            "l0_over_dy": l0_phys_est / max(dy, 1e-20),
            "l0_over_dz": l0_phys_est / max(dz, 1e-20),
        },
        "loading_scaling": {
            "max_strain": max_strain,
            "u_peak_m_from_epsLx": u_peak,
            f"u_peak_{u_name}_from_epsLx": u_peak * sc,
            "max_strain_step": float(vc.get("max_strain_step", float("nan"))),
        },
        "arc_notch_scaling": {
            "raw_width_m": raw_w,
            "effective_width_m": eff_w,
            "min_cells_x": min_cells,
            f"raw_width_{u_name}": None if raw_w is None else raw_w * sc,
            f"effective_width_{u_name}": None if eff_w is None else eff_w * sc,
        },
    }

    _write_json(out_dir / "scale_consistency_report.json", report)

    lines = [
        "# Scale Consistency Report",
        "",
        f"- Grid: `{shape}`",
        f"- Spacing ({u_name}): `{dx*sc:.4f}, {dy*sc:.4f}, {dz*sc:.4f}`",
        f"- Domain ({u_name}): `{lx*sc:.3f} x {ly*sc:.3f} x {lz*sc:.3f}`",
        f"- Stress ref: `{stress_ref_gpa:.3f} GPa`",
        f"- Estimated E[111]: `{e111:.3f} GPa`",
        f"- l0/dx (effective): `{report['fracture_scaling']['l0_over_dx']:.3f}`",
        f"- Peak displacement from eps*Lx ({u_name}): `{u_peak*sc:.6f}`",
    ]
    if raw_w is not None:
        lines.append(f"- Arc-notch width raw/effective ({u_name}): `{raw_w*sc:.4f} / {eff_w*sc:.4f}`")
    (out_dir / "scale_consistency_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    return report


def _run_subprocess(cmd: list[str], cwd: Path, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(cmd, cwd=str(cwd), check=check, text=True, capture_output=True)


def _mesh_case_shape(base_shape: tuple[int, int, int], factor: float) -> tuple[int, int, int]:
    nx = max(8, int(round(base_shape[0] * factor)))
    ny = max(6, int(round(base_shape[1] * factor)))
    nz = max(4, int(round(base_shape[2] * factor)))
    return nx, ny, nz


def _mesh_convergence_step(
    base_vc: dict[str, Any],
    out_root: Path,
    python_bin: str,
    mesh_factors: list[float],
    target_amp_pct: float,
    cycles: int,
    cycle_points: int,
) -> dict[str, Any]:
    base_shape = tuple(int(v) for v in base_vc.get("grid_shape", (24, 12, 4)))
    base_spacing = tuple(float(v) for v in base_vc.get("grid_spacing", (1.0, 1.0, 1.0)))
    base_l = tuple((base_shape[i] - 1) * base_spacing[i] for i in range(3))
    stress_ref_gpa = float(base_vc.get("stress_ref_gpa", 168.4))

    cfg_dir = out_root / "configs"
    out_dir = out_root / "outputs"
    run_dir = out_root / "runs"
    for d in (cfg_dir, out_dir, run_dir):
        d.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    for f in mesh_factors:
        shape = _mesh_case_shape(base_shape, f)
        spacing = tuple(base_l[i] / max(shape[i] - 1, 1) for i in range(3))

        vc = json.loads(json.dumps(base_vc))
        vc["grid_shape"] = [int(v) for v in shape]
        vc["grid_spacing"] = [float(v) for v in spacing]
        vc["max_strain"] = float(target_amp_pct / 100.0)
        vc["task"] = f"priority4_mesh_f{f:.2f}".replace(".", "p")
        vc["mech_accept_rel_residual"] = max(float(vc.get("mech_accept_rel_residual", 0.0)), 1.5)
        vc["mech_accept_incomplete_cg"] = True
        vc["mech_accept_incomplete_without_residual"] = True
        vc["adaptive_substep_retry"] = True
        vc["adaptive_substep_max_splits"] = max(int(vc.get("adaptive_substep_max_splits", 8)), 14)
        vc["adaptive_substep_min_increment"] = min(float(vc.get("adaptive_substep_min_increment", 1.0e-8)), 1.0e-10)
        vc["max_strain_step"] = min(float(vc.get("max_strain_step", 1.0e-3)), 2.0e-4)

        tag = f"mesh_{shape[0]}x{shape[1]}x{shape[2]}"
        cfg_path = cfg_dir / f"{tag}.yaml"
        case_out = out_dir / tag
        case_run = run_dir / tag
        _dump_yaml(cfg_path, vc)

        cmd = [
            python_bin,
            "sim/tests/run_coupled_validation_bundle.py",
            "--config",
            str(cfg_path),
            "--out-dir",
            str(case_out),
            "--run-dir",
            str(case_run),
            "--cycles",
            str(int(cycles)),
            "--cycle-points",
            str(int(cycle_points)),
            "--keep-old-images",
        ]
        proc = _run_subprocess(cmd, ROOT, check=False)
        status = "ok"
        err_msg = ""

        if proc.returncode != 0:
            # One retry with relaxed acceptance and stronger adaptive splitting.
            status = "retry"
            vc_retry = json.loads(json.dumps(vc))
            vc_retry["mech_accept_rel_residual"] = max(float(vc_retry.get("mech_accept_rel_residual", 0.0)), 2.0)
            vc_retry["mech_accept_incomplete_cg"] = True
            vc_retry["mech_accept_incomplete_without_residual"] = True
            vc_retry["adaptive_substep_retry"] = True
            vc_retry["adaptive_substep_max_splits"] = max(int(vc_retry.get("adaptive_substep_max_splits", 8)), 12)
            vc_retry["adaptive_substep_min_increment"] = min(
                float(vc_retry.get("adaptive_substep_min_increment", 1.0e-8)),
                1.0e-10,
            )
            cfg_retry = cfg_dir / f"{tag}_retry.yaml"
            _dump_yaml(cfg_retry, vc_retry)
            cmd_retry = cmd.copy()
            cmd_retry[cmd_retry.index("--config") + 1] = str(cfg_retry)
            proc2 = _run_subprocess(cmd_retry, ROOT, check=False)
            if proc2.returncode != 0:
                status = "failed"
                err_msg = (proc2.stderr or proc2.stdout or "").strip()[-1200:]
            else:
                status = "ok_retry"
                proc = proc2

        summary_path = case_out / "validation_bundle_summary.json"
        if summary_path.exists():
            summary = json.loads(summary_path.read_text(encoding="utf-8"))
            curve_csv = case_out / "validation_sigma_a_vs_cum.csv"
            hratio = _hardening_ratio(curve_csv)
            closure = _loop_closure_ratio(
                case_run / "virtual_cycle_stress_strain.csv",
                cycle_points=cycle_points,
                stress_ref_gpa=stress_ref_gpa,
            )
            cycles_completed = int(summary.get("cycles_completed", 0))
            crack_mean_t1 = float(summary.get("crack_mean_t1", float("nan")))
            crack_p95_t1 = float(summary.get("crack_p95_t1", float("nan")))
            accum_plastic_mean_t1 = float(summary.get("accum_plastic_mean_t1", float("nan")))
            gnd_mean_t1 = float(summary.get("gnd_mean_t1", float("nan")))
            gnd_max_t1 = float(summary.get("gnd_max_t1", float("nan")))
        else:
            hratio = float("nan")
            closure = float("nan")
            cycles_completed = 0
            crack_mean_t1 = float("nan")
            crack_p95_t1 = float("nan")
            accum_plastic_mean_t1 = float("nan")
            gnd_mean_t1 = float("nan")
            gnd_max_t1 = float("nan")

        rows.append(
            {
                "mesh_tag": tag,
                "factor": f,
                "nx": shape[0],
                "ny": shape[1],
                "nz": shape[2],
                "dx_m": spacing[0],
                "dy_m": spacing[1],
                "dz_m": spacing[2],
                "status": status,
                "cycles_completed": cycles_completed,
                "crack_mean_t1": crack_mean_t1,
                "crack_p95_t1": crack_p95_t1,
                "accum_plastic_mean_t1": accum_plastic_mean_t1,
                "gnd_mean_t1": gnd_mean_t1,
                "gnd_max_t1": gnd_max_t1,
                "loop_closure_ratio": closure,
                "hardening_ratio": hratio,
                "error_tail": err_msg,
                "case_out": str(case_out),
                "case_run": str(case_run),
            }
        )

    rows_sorted = sorted(rows, key=lambda r: (int(r["nx"]) * int(r["ny"]) * int(r["nz"])))
    finite_sorted = [r for r in rows_sorted if np.isfinite(float(r.get("crack_p95_t1", float("nan"))))]
    ref = finite_sorted[-1] if finite_sorted else rows_sorted[-1]
    for r in rows_sorted:
        for k in ("crack_p95_t1", "accum_plastic_mean_t1", "gnd_mean_t1", "loop_closure_ratio"):
            rv = float(r.get(k, float("nan")))
            rf = float(ref.get(k, float("nan")))
            if np.isfinite(rv) and np.isfinite(rf) and abs(rf) > 1e-14:
                r[f"rel_err_vs_finest_{k}"] = abs(rv - rf) / abs(rf)
            else:
                r[f"rel_err_vs_finest_{k}"] = float("nan")

    fields = [
        "mesh_tag",
        "factor",
        "nx",
        "ny",
        "nz",
        "dx_m",
        "dy_m",
        "dz_m",
        "status",
        "cycles_completed",
        "crack_mean_t1",
        "crack_p95_t1",
        "accum_plastic_mean_t1",
        "gnd_mean_t1",
        "gnd_max_t1",
        "loop_closure_ratio",
        "hardening_ratio",
        "error_tail",
        "rel_err_vs_finest_crack_p95_t1",
        "rel_err_vs_finest_accum_plastic_mean_t1",
        "rel_err_vs_finest_gnd_mean_t1",
        "rel_err_vs_finest_loop_closure_ratio",
        "case_out",
        "case_run",
    ]
    _write_csv(out_root / "mesh_convergence_metrics.csv", rows_sorted, fields)
    summary = {
        "target_amp_percent": target_amp_pct,
        "cycles": cycles,
        "cycle_points": cycle_points,
        "mesh_factors": mesh_factors,
        "reference_finest": ref,
        "cases": rows_sorted,
    }
    _write_json(out_root / "mesh_convergence_summary.json", summary)
    return summary


@dataclass(frozen=True)
class BackstressCandidate:
    name: str
    kin_c_scale: float
    kin_d_scale: float
    kin_c2_scale: float
    kin_d2_scale: float


def _default_backstress_candidates() -> list[BackstressCandidate]:
    return [
        BackstressCandidate("base", 1.0, 1.0, 1.0, 1.0),
        BackstressCandidate("bs_moderate", 1.15, 0.95, 1.8, 0.9),
        BackstressCandidate("bs_strong", 1.35, 0.85, 2.4, 0.8),
        BackstressCandidate("bs_stronger", 1.55, 0.75, 3.0, 0.7),
        BackstressCandidate("bs_dual_fast", 1.25, 0.9, 3.2, 0.6),
    ]


def _score_candidate(case_rows: list[dict[str, Any]]) -> tuple[float, dict[str, float]]:
    closures = np.array([float(r.get("loop_closure_ratio", float("nan"))) for r in case_rows], dtype=float)
    hardens = np.array([float(r.get("hardening_ratio", float("nan"))) for r in case_rows], dtype=float)
    cycles_done = np.array([float(r.get("cycles_completed", 0.0)) for r in case_rows], dtype=float)
    ok_arr = np.array([1.0 if bool(r.get("ok", False)) else 0.0 for r in case_rows], dtype=float)

    closure_mean = float(np.nanmean(closures)) if np.isfinite(np.nanmean(closures)) else 0.0
    hard_log = np.log10(np.clip(hardens, 1.0e-6, None))
    hard_mean = float(np.nanmean(hard_log)) if np.isfinite(np.nanmean(hard_log)) else -6.0
    cycles_min = float(np.nanmin(cycles_done)) if cycles_done.size > 0 else 0.0
    success_rate = float(np.mean(ok_arr)) if ok_arr.size > 0 else 0.0

    score = 0.55 * closure_mean + 0.20 * hard_mean + 0.10 * min(cycles_min, 6.0) + 0.15 * success_rate
    return score, {
        "closure_mean": closure_mean,
        "hardening_log10_mean": hard_mean,
        "cycles_completed_min": cycles_min,
        "success_rate": success_rate,
    }


def _calibration_step(
    base_vc: dict[str, Any],
    out_root: Path,
    python_bin: str,
    amplitudes: list[float],
    cycles: int,
    cycle_points: int,
    max_candidates: int,
) -> dict[str, Any]:
    cfg_dir = out_root / "configs"
    out_dir = out_root / "outputs"
    run_dir = out_root / "runs"
    for d in (cfg_dir, out_dir, run_dir):
        d.mkdir(parents=True, exist_ok=True)

    stress_ref_gpa = float(base_vc.get("stress_ref_gpa", 168.4))
    candidates = _default_backstress_candidates()[: max(1, max_candidates)]
    rows_rank: list[dict[str, Any]] = []

    base_kin_c = float(base_vc.get("kin_c", 0.022))
    base_kin_d = float(base_vc.get("kin_d", 10.0))
    base_kin_c2 = float(base_vc.get("kin_c2", 0.0025))
    base_kin_d2 = float(base_vc.get("kin_d2", 1.0))

    for cand in candidates:
        vc = json.loads(json.dumps(base_vc))
        vc["task"] = f"priority4_calib_{cand.name}"

        # Keep Cu elasticity/plastic baseline unchanged; only strengthen reverse hardening by dual backstress.
        vc["kin_c"] = base_kin_c * cand.kin_c_scale
        vc["kin_d"] = base_kin_d * cand.kin_d_scale
        vc["kin_c2"] = base_kin_c2 * cand.kin_c2_scale
        vc["kin_d2"] = base_kin_d2 * cand.kin_d2_scale

        # Enforce displacement-driven BC and non-dimensional kinematics for stability.
        vc["mech_displacement_bc_x"] = True
        vc["mech_displacement_bc_hard"] = True
        vc["mech_nondim_kinematics"] = True
        vc["mech_accept_rel_residual"] = max(float(vc.get("mech_accept_rel_residual", 0.0)), 1.5)
        vc["mech_accept_incomplete_cg"] = True
        vc["mech_accept_incomplete_without_residual"] = True
        vc["adaptive_substep_retry"] = True
        vc["adaptive_substep_max_splits"] = max(int(vc.get("adaptive_substep_max_splits", 8)), 14)
        vc["adaptive_substep_min_increment"] = min(float(vc.get("adaptive_substep_min_increment", 1.0e-8)), 1.0e-10)
        vc["max_strain_step"] = min(float(vc.get("max_strain_step", 1.0e-3)), 2.0e-4)

        cfg_path = cfg_dir / f"calib_{cand.name}.yaml"
        _dump_yaml(cfg_path, vc)

        case_out = out_dir / cand.name
        case_run = run_dir / cand.name
        (case_out).mkdir(parents=True, exist_ok=True)
        (case_run).mkdir(parents=True, exist_ok=True)

        per_amp_rows: list[dict[str, Any]] = []
        failed_msgs: list[str] = []
        for amp in amplitudes:
            amp_tag = str(amp).replace(".", "p")
            amp_case_name = f"amp_{amp_tag}pct"
            amp_out = case_out / amp_case_name
            amp_run = case_run / amp_case_name
            amp_out.mkdir(parents=True, exist_ok=True)
            amp_run.mkdir(parents=True, exist_ok=True)
            r = _run_validation_case(
                vc,
                amp_pct=float(amp),
                cfg_dir=case_run / "configs",
                out_dir=amp_out,
                run_dir=amp_run,
                python_bin=python_bin,
                cycles=cycles,
                cycle_points=cycle_points,
                case_tag=f"{cand.name}_{amp_case_name}",
            )

            closure = _loop_closure_ratio(
                amp_run / "virtual_cycle_stress_strain.csv",
                cycle_points=cycle_points,
                stress_ref_gpa=stress_ref_gpa,
            ) if r["ok"] else float("nan")
            hratio = _hardening_ratio(amp_out / "validation_sigma_a_vs_cum.csv") if r["ok"] else float("nan")
            cycles_completed = 0
            if r["ok"]:
                try:
                    sm = json.loads((amp_out / "validation_bundle_summary.json").read_text(encoding="utf-8"))
                    cycles_completed = int(sm.get("cycles_completed", 0))
                except Exception:
                    cycles_completed = 0
            if not r["ok"]:
                failed_msgs.append(f"{amp_case_name}:{r['error_tail']}")
            per_amp_rows.append(
                {
                    "case": amp_case_name,
                    "ok": bool(r["ok"]),
                    "loop_closure_ratio": closure,
                    "hardening_ratio": hratio,
                    "cycles_completed": int(cycles_completed),
                    "error_tail": r["error_tail"],
                }
            )

        score, comps = _score_candidate(per_amp_rows)
        row = {
            "candidate": cand.name,
            "kin_c": vc["kin_c"],
            "kin_d": vc["kin_d"],
            "kin_c2": vc["kin_c2"],
            "kin_d2": vc["kin_d2"],
            "score": score,
            **comps,
            "error_tail": " | ".join([m for m in failed_msgs if m][:3]),
            "case_out": str(case_out),
            "case_run": str(case_run),
        }
        rows_rank.append(row)

        _write_csv(
            case_out / "calibration_per_amplitude_metrics.csv",
            per_amp_rows,
            ["case", "ok", "loop_closure_ratio", "hardening_ratio", "cycles_completed", "error_tail"],
        )

    rows_rank.sort(key=lambda r: float(r["score"]), reverse=True)
    best = rows_rank[0]

    _write_csv(
        out_root / "calibration_ranking.csv",
        rows_rank,
        [
            "candidate",
            "kin_c",
            "kin_d",
            "kin_c2",
            "kin_d2",
            "score",
            "closure_mean",
            "hardening_log10_mean",
            "cycles_completed_min",
            "success_rate",
            "error_tail",
            "case_out",
            "case_run",
        ],
    )
    summary = {
        "amplitudes_percent": amplitudes,
        "cycles": cycles,
        "cycle_points": cycle_points,
        "ranking": rows_rank,
        "best": best,
    }
    _write_json(out_root / "calibration_summary.json", summary)

    best_cfg = json.loads(json.dumps(base_vc))
    best_cfg["task"] = "priority4_best_dual_backstress"
    best_cfg["kin_c"] = float(best["kin_c"])
    best_cfg["kin_d"] = float(best["kin_d"])
    best_cfg["kin_c2"] = float(best["kin_c2"])
    best_cfg["kin_d2"] = float(best["kin_d2"])
    best_cfg["mech_displacement_bc_x"] = True
    best_cfg["mech_displacement_bc_hard"] = True
    best_cfg["mech_nondim_kinematics"] = True
    best_cfg["mech_accept_rel_residual"] = max(float(best_cfg.get("mech_accept_rel_residual", 0.0)), 1.5)
    best_cfg["mech_accept_incomplete_cg"] = True
    best_cfg["mech_accept_incomplete_without_residual"] = True
    best_cfg["adaptive_substep_retry"] = True
    best_cfg["adaptive_substep_max_splits"] = max(int(best_cfg.get("adaptive_substep_max_splits", 8)), 14)
    best_cfg["adaptive_substep_min_increment"] = min(float(best_cfg.get("adaptive_substep_min_increment", 1.0e-8)), 1.0e-10)
    best_cfg["max_strain_step"] = min(float(best_cfg.get("max_strain_step", 1.0e-3)), 2.0e-4)
    best_cfg_path = out_root / "best_dual_backstress_config.yaml"
    _dump_yaml(best_cfg_path, best_cfg)
    summary["best_config"] = str(best_cfg_path)
    _write_json(out_root / "calibration_summary.json", summary)
    return summary


def _unified_validation_step(
    best_cfg_path: Path,
    out_root: Path,
    python_bin: str,
    amplitudes: list[float],
    cycles: int,
    cycle_points: int,
) -> dict[str, Any]:
    out_dir = out_root / "outputs"
    run_dir = out_root / "runs"
    cfg_dir = out_root / "configs"
    out_dir.mkdir(parents=True, exist_ok=True)
    run_dir.mkdir(parents=True, exist_ok=True)
    cfg_dir.mkdir(parents=True, exist_ok=True)

    best_cfg = _load_vc(best_cfg_path)
    stress_ref_gpa = float(best_cfg.get("stress_ref_gpa", 168.4))

    index_rows: list[dict[str, Any]] = []
    run_errors: list[dict[str, Any]] = []
    for amp in amplitudes:
        amp_tag = str(amp).replace(".", "p")
        case_name = f"amp_{amp_tag}pct"
        case_out = out_dir / case_name
        case_run = run_dir / case_name
        case_out.mkdir(parents=True, exist_ok=True)
        case_run.mkdir(parents=True, exist_ok=True)
        r = _run_validation_case(
            best_cfg,
            amp_pct=float(amp),
            cfg_dir=cfg_dir,
            out_dir=case_out,
            run_dir=case_run,
            python_bin=python_bin,
            cycles=cycles,
            cycle_points=cycle_points,
            case_tag=f"final_{case_name}",
        )
        if not r["ok"]:
            run_errors.append({"case": case_name, "error_tail": r["error_tail"]})
        index_rows.append(
            {
                "case": case_name,
                "total_strain_amplitude_percent": float(amp),
                "max_strain_used": float(amp) / 100.0,
                "run_dir": str(case_run),
                "grod_png": str(case_out / "validation_grod_t1.png"),
                "accum_plastic_png": str(case_out / "validation_accum_plastic_t1.png"),
                "crack_png": str(case_out / "validation_crack_t1.png"),
                "sigma_a_png": str(case_out / "validation_sigma_a_vs_cum.png"),
                "sigma_a_csv": str(case_out / "validation_sigma_a_vs_cum.csv"),
                "slip_table_png": str(case_out / "validation_slip_damage_schmid_table.png"),
                "slip_table_csv": str(case_out / "validation_slip_damage_schmid.csv"),
                "cycles_completed": int(
                    json.loads((case_out / "validation_bundle_summary.json").read_text(encoding="utf-8")).get("cycles_completed", 0)
                ) if (case_out / "validation_bundle_summary.json").exists() else 0,
                "ok": bool(r["ok"]),
            }
        )

    _write_csv(
        out_root / "multi_amplitude_validation_index.csv",
        index_rows,
        [
            "case",
            "total_strain_amplitude_percent",
            "max_strain_used",
            "run_dir",
            "grod_png",
            "accum_plastic_png",
            "crack_png",
            "sigma_a_png",
            "sigma_a_csv",
            "slip_table_png",
            "slip_table_csv",
            "cycles_completed",
            "ok",
        ],
    )

    qc_rows: list[dict[str, Any]] = []
    for row in index_rows:
        case = str(row.get("case", ""))
        curve_csv = Path(str(row.get("sigma_a_csv", "")))
        run_case_dir = Path(str(row.get("run_dir", "")))
        if not run_case_dir.is_absolute():
            run_case_dir = (ROOT / run_case_dir).resolve()

        closure = _loop_closure_ratio(
            run_case_dir / "virtual_cycle_stress_strain.csv",
            cycle_points=cycle_points,
            stress_ref_gpa=stress_ref_gpa,
        )
        hratio = _hardening_ratio(curve_csv)
        cycles_done = int(float(row.get("cycles_completed", 0)))

        qc_rows.append(
            {
                "case": case,
                "cycles_completed": cycles_done,
                "loop_closure_ratio": closure,
                "hardening_ratio": hratio,
                "ok": bool(row.get("ok", False)),
                "pass_cycles_ge3": cycles_done >= 3,
                "pass_closure_ge_0p05": bool(np.isfinite(closure) and closure >= 0.05),
                "pass_hardening_ratio_ge_1p2": bool(np.isfinite(hratio) and hratio >= 1.2),
                "grod_png": row.get("grod_png", ""),
                "sigma_a_png": row.get("sigma_a_png", ""),
                "slip_table_png": row.get("slip_table_png", ""),
            }
        )

    _write_csv(
        out_root / "unified_validation_qc.csv",
        qc_rows,
        [
            "case",
            "cycles_completed",
            "loop_closure_ratio",
            "hardening_ratio",
            "ok",
            "pass_cycles_ge3",
            "pass_closure_ge_0p05",
            "pass_hardening_ratio_ge_1p2",
            "grod_png",
            "sigma_a_png",
            "slip_table_png",
        ],
    )
    summary2 = {
        "best_config": str(best_cfg_path),
        "cycles": cycles,
        "cycle_points": cycle_points,
        "amplitudes_percent": amplitudes,
        "run_errors": run_errors,
        "qc_rows": qc_rows,
    }
    _write_json(out_root / "unified_validation_summary.json", summary2)
    return summary2


def main() -> int:
    parser = argparse.ArgumentParser(description="Run priority-4 fatigue workflow (scale->mesh->calib->validation).")
    parser.add_argument(
        "--base-config",
        type=Path,
        default=Path(
            "sim/configs/fatigue_lowamp_align_locked_v5_hard_sat_coupled_arc_macro500um_notch_x0p1_scalefix_noclip_smallstep.yaml"
        ),
    )
    parser.add_argument(
        "--out-root",
        type=Path,
        default=Path("docs/exp_compare_cycle_1000") / f"priority4_pipeline_{_now_tag()}",
    )
    parser.add_argument("--python", type=str, default=sys.executable)
    parser.add_argument("--amplitudes", type=str, default="0.2,0.4,0.6,0.8")
    parser.add_argument("--mesh-factors", type=str, default="0.8,1.0,1.2")
    parser.add_argument("--mesh-amp", type=float, default=0.4, help="Total strain amplitude percent for mesh convergence.")
    parser.add_argument("--cycles", type=int, default=4)
    parser.add_argument("--cycle-points", type=int, default=48)
    parser.add_argument("--max-candidates", type=int, default=4)
    args = parser.parse_args()

    amps = [float(x.strip()) for x in str(args.amplitudes).split(",") if x.strip()]
    mesh_factors = [float(x.strip()) for x in str(args.mesh_factors).split(",") if x.strip()]
    if not amps:
        raise ValueError("--amplitudes parsed empty.")
    if not mesh_factors:
        raise ValueError("--mesh-factors parsed empty.")

    out_root = args.out_root
    out_root.mkdir(parents=True, exist_ok=True)
    (out_root / "configs").mkdir(parents=True, exist_ok=True)

    base_vc = _load_vc(args.base_config)

    step1_dir = out_root / "step1_scale_consistency"
    step2_dir = out_root / "step2_mesh_convergence"
    step3_dir = out_root / "step3_dual_backstress_calibration"
    step4_dir = out_root / "step4_unified_validation"

    step1 = _scale_consistency_step(base_vc, step1_dir)

    step2 = _mesh_convergence_step(
        base_vc,
        out_root=step2_dir,
        python_bin=args.python,
        mesh_factors=mesh_factors,
        target_amp_pct=float(args.mesh_amp),
        cycles=int(args.cycles),
        cycle_points=int(args.cycle_points),
    )

    step3 = _calibration_step(
        base_vc,
        out_root=step3_dir,
        python_bin=args.python,
        amplitudes=amps,
        cycles=int(args.cycles),
        cycle_points=int(args.cycle_points),
        max_candidates=int(args.max_candidates),
    )

    best_cfg_path = Path(str(step3["best_config"]))
    step4 = _unified_validation_step(
        best_cfg_path,
        out_root=step4_dir,
        python_bin=args.python,
        amplitudes=amps,
        cycles=int(args.cycles),
        cycle_points=int(args.cycle_points),
    )

    summary = {
        "base_config": str(args.base_config),
        "out_root": str(out_root),
        "step1": str(step1_dir),
        "step2": str(step2_dir),
        "step3": str(step3_dir),
        "step4": str(step4_dir),
        "best_config": str(best_cfg_path),
        "mesh_reference": step2.get("reference_finest", {}),
        "calibration_best": step3.get("best", {}),
        "qc_cases": step4.get("qc_rows", []),
    }
    _write_json(out_root / "priority4_pipeline_summary.json", summary)

    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
